apiVersion: v1
kind: Service
metadata:
  name: pulsedesk-service
  namespace: ${NAMESPACE}
  labels:
    app: pulsedesk
spec:
  type: ClusterIP
  selector:
    app: pulsedesk
  ports:
    - port: 80
      targetPort: 8080
