apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: ${NAMESPACE}
  labels:
    app: pulsedesk

spec:
  provider: aws

  parameters:
    objects: |
      - objectName: "backend-${NAMESPACE}"
        objectType: "secretsmanager"
        jmesPath:
          - path: PULSEDESK_DB_URL
            objectAlias: PULSEDESK_DB_URL
          - path: PULSEDESK_DB_USERNAME
            objectAlias: PULSEDESK_DB_USERNAME
          - path: PULSEDESK_DB_PASSWORD
            objectAlias: PULSEDESK_DB_PASSWORD
          - path: PULSEDESK_KAFKA_BOOTSTRAP_SERVERS
            objectAlias: PULSEDESK_KAFKA_BOOTSTRAP_SERVERS
