pipeline {
    agent {
        node {
            label 'Maven'
        }
    }

    /***********************
     * PARAMETERS (UI)
     ***********************/
    parameters {
        gitParameter(
            name: 'BRANCH',
            type: 'PT_BRANCH',
            defaultValue: 'main',
            branchFilter: 'origin/(.*)',
            description: 'Select Git branch'
        )

        choice(
            name: 'ENVIRONMENT',
            choices: ['dev', 'uat', 'prod'],
            description: 'Deployment environment'
        )

        string(
            name: 'IMAGE_NAME',
            defaultValue: 'pulsedesk',
            description: 'Docker image name'
        )

        string(
            name: 'REPLICAS',
            defaultValue: '1',
            description: 'Number of pod replicas'
        )

        string(
            name: 'REQUEST_CPU',
            defaultValue: '250m',
            description: 'CPU request'
        )

        string(
            name: 'REQUEST_MEMORY',
            defaultValue: '512Mi',
            description: 'Memory request'
        )

        string(
            name: 'LIMIT_CPU',
            defaultValue: '500m',
            description: 'CPU limit'
        )

        string(
            name: 'LIMIT_MEMORY',
            defaultValue: '1024Mi',
            description: 'Memory limit'
        )
    }

    /***********************
     * ENVIRONMENT VARS
     ***********************/
    environment {
        PATH = "/opt/maven/bin:$PATH"

        AWS_ACCOUNT_ID = "735235878184"
        AWS_REGION     = "us-east-2"

        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${params.IMAGE_NAME}:${IMAGE_TAG}"

        NAMESPACE = "${params.ENVIRONMENT}"
        SPRING_PROFILE = "${params.ENVIRONMENT}"
    }

    stages {

        stage('Build & Test') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Code Quality - SonarQube') {
            environment {
                scannerHome = tool 'eventcart-sonar-scanner'
            }
            steps {
                withSonarQubeEnv(
                    installationName: 'sonarqube-server-local',
                    credentialsId: 'sonarqubeLocalhost'
                ) {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    script {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            error "Pipeline aborted due to quality gate failure: ${qg.status}"
                        }
                    }
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                sh """
                  aws ecr get-login-password --region ${AWS_REGION} \
                  | docker login --username AWS --password-stdin \
                    ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                  docker build -t ${IMAGE_URI} .
                  docker push ${IMAGE_URI}
                  docker rmi ${IMAGE_URI} || true
                """
            }
        }

        stage('Deploy to EKS') {
            steps {
                sh """
                  aws eks update-kubeconfig \
                    --region ${AWS_REGION} \
                    --name backend-eks

                  export IMAGE_URI=${IMAGE_URI}
                  export NAMESPACE=${NAMESPACE}
                  export REPLICAS=${params.REPLICAS}
                  export SPRING_PROFILE=${SPRING_PROFILE}
                  export REQUEST_CPU=${params.REQUEST_CPU}
                  export REQUEST_MEMORY=${params.REQUEST_MEMORY}
                  export LIMIT_CPU=${params.LIMIT_CPU}
                  export LIMIT_MEMORY=${params.LIMIT_MEMORY}

                  kubectl get ns ${NAMESPACE} || kubectl create ns ${NAMESPACE}

					envsubst < k8s/secretproviderclass.yaml | kubectl apply -f -
					envsubst < k8s/deployment.yaml | kubectl apply -f -
					envsubst < k8s/service.yaml | kubectl apply -f -
                """
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful to ${ENVIRONMENT}"
        }
        failure {
            echo "❌ Pipeline failed"
        }
    }
}
