spring.application.name=pulsedesk-assignment-service
server.port=0
pulsedesk.base-url=${PULSEDESK_BASE_URL:http://localhost:80}

spring.kafka.bootstrap-servers=3.145.127.180:9092,3.145.127.180:9094,3.145.127.180:9096
#spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9094, localhost:9096
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.group-id=pulsedesk-ticket-assignment-group
